/**
 * Ambient type declarations for the `supersolid` authoring API.
 *
 * These types exist ONLY for the editor / TypeScript language server. superui's
 * Rust transpiler is the real consumer of `.tsx`: it strips the types and erases
 * the `import ... from "supersolid"` — the reactive primitives and control-flow
 * components are injected by the runtime (the `$ss.*` ABI). Nothing here affects
 * the build or runtime; it only powers autocomplete, hover docs, and type-checking.
 *
 * Do NOT edit this file inside a project — it is projected (copied) by
 * `cargo superui install` and will be overwritten. Edit the canonical copy at
 * `crates/supersolid/supersolid.d.ts`.
 */

declare module "supersolid" {
  /**
   * A reactive getter. Call it to read the current value AND — inside a tracking
   * scope (effect, memo, or JSX expression) — subscribe to future changes:
   * `count()`. Reading is what subscribes; there is no separate `.subscribe`.
   */
  export type Accessor<T> = () => T;
  /**
   * Writes a signal's value, re-running exactly the bindings that read it.
   * Accepts either a new value or an updater that receives the previous value.
   * @example setCount(5); setCount((n) => n + 1);
   */
  export type Setter<T> = (value: T | ((prev: T) => T)) => void;

  /**
   * Create a reactive signal — the fundamental unit of state.
   *
   * Returns a `[get, set]` tuple. Reading `get()` inside a tracking scope
   * subscribes that scope; `set(v)` re-runs exactly the subscribers that read it.
   * Components run once, so keep reads inline (`{count()}`) rather than caching
   * them in a variable at the top of the body.
   *
   * @example
   * const [count, setCount] = createSignal(0);
   * // in JSX:  <button onClick={() => setCount(count() + 1)}>{count()}</button>
   */
  export function createSignal<T>(value?: T): [Accessor<T>, Setter<T>];

  /**
   * Run a side effect that re-executes whenever any signal it reads changes.
   * The body runs once immediately, tracking its reactive reads.
   * @example createEffect(() => console.log("count is", count()));
   */
  export function createEffect(fn: () => void): void;

  /**
   * Create a derived, memoized signal. `fn` re-runs when its reactive
   * dependencies change; readers update only when the result actually changes.
   * Use for expensive or shared derivations.
   * @example const doubled = createMemo(() => count() * 2);
   */
  export function createMemo<T>(fn: () => T): Accessor<T>;

  /** Register a callback to run once, after the component's initial render. */
  export function onMount(fn: () => void): void;

  /**
   * Register cleanup to run when the enclosing reactive scope is disposed
   * (component unmounts, or a list row is removed).
   */
  export function onCleanup(fn: () => void): void;

  /** Read signals without subscribing — reads inside `fn` are not tracked. */
  export function untrack<T>(fn: () => T): T;

  /** Batch multiple writes so dependents recompute once, at the end. */
  export function batch<T>(fn: () => T): T;

  /** An injectable context created by {@link createContext}. */
  export interface Context<T> {
    readonly id: number;
    readonly defaultValue: T;
  }
  /**
   * Create a context carrying `defaultValue` for descendants to read via
   * {@link useContext}.
   */
  export function createContext<T>(defaultValue: T): Context<T>;
  /** Read the nearest provided value for `context` (or its default). */
  export function useContext<T>(context: Context<T>): T;

  /**
   * Mount a component tree into a DOM node. Call once at app entry.
   * @param code A function returning the root element (usually `() => <App/>`).
   * @param mount The container node to render into.
   */
  export function render(code: () => unknown, mount: unknown): void;

  // ---- Control-flow components ---------------------------------------------
  // Permissive on purpose: these are markup for a browser-like arena DOM, not
  // React elements. Inside a plain element, wrap them in `{...}`.

  /**
   * Render a list, re-mapping each item by IDENTITY across changes (a row is
   * reused when its item object survives a reorder). Prefer over {@link Index}
   * when list order matters.
   * @example <For each={items()}>{(item, i) => <li>{item.name}</li>}</For>
   */
  export const For: <T>(props: {
    each: readonly T[] | undefined | null;
    children: (item: T, index: Accessor<number>) => unknown;
  }) => unknown;

  /**
   * Render a list keyed by POSITION: the item is a signal, the index is fixed.
   * Prefer over {@link For} when items are primitives or only values change.
   * @example <Index each={rows()}>{(row, i) => <li>{row().label}</li>}</Index>
   */
  export const Index: <T>(props: {
    each: readonly T[] | undefined | null;
    children: (item: Accessor<T>, index: number) => unknown;
  }) => unknown;

  /**
   * Conditionally render `children` when `when` is truthy.
   * @example <Show when={loaded()}>{<Content />}</Show>
   */
  export const Show: (props: { when: unknown; children: unknown }) => unknown;

  /**
   * Overlay-style keyed list: reuse a mapped node per item identity WITHOUT
   * enforcing DOM order. Correct for absolutely-positioned overlays; use
   * {@link For} when order matters. `by` names the identity key field on each
   * item; the child receives the item (a fine-grained reactive row proxy).
   * @example <Keyed each={blips()} by="id">{(b) => <div class={b.kind} />}</Keyed>
   */
  export const Keyed: <T>(props: {
    each: readonly T[] | undefined | null;
    by: keyof T & string;
    children: (item: T) => unknown;
  }) => unknown;

  /**
   * Render the first matching {@link Match} child.
   * @example
   * <Switch>
   *   <Match when={loading()}>{<Spinner />}</Match>
   *   <Match when={error()}>{<ErrorView />}</Match>
   * </Switch>
   */
  export const Switch: (props: { children: unknown }) => unknown;
  /** A branch of {@link Switch}; renders `children` when `when` is truthy. */
  export const Match: (props: { when: unknown; children: unknown }) => unknown;
}

// ---------------------------------------------------------------------------
// With `jsx: preserve` and no jsxImportSource, TypeScript resolves intrinsic
// elements against the GLOBAL JSX namespace. Keep it permissive: this is markup
// for a browser-like arena DOM, not React, so React's element typings must not
// apply.
declare namespace JSX {
  interface IntrinsicElements {
    [name: string]: any;
  }
  type Element = any;
  interface ElementChildrenAttribute {
    children: {};
  }
}

// ---------------------------------------------------------------------------
// The `window.bevy` bridge — the one NON-web global superui injects. The
// standard web globals it also provides (document, console, setTimeout, fetch,
// window) come from the DOM lib (see the tsconfig `lib`), so only `bevy`, which
// is superui-specific, is declared here.

/** The superui JS↔Bevy bridge — the JS↔ECS channel. Also reachable as `window.bevy`. */
interface Bevy {
  /**
   * Fire a registered command into the game: triggers the Bevy `Event` bound to
   * `name` on the Rust side, deserializing `data` (as JSON) into that event type.
   * Unregistered names warn and no-op. Pass a type argument to check the payload
   * against your command's shape.
   * @example bevy.send("HordeIntent", { kind: "StartGame", index: 0 });
   * @example bevy.send<AdjustEnemyCap>("AdjustEnemyCap", { delta: -20 });
   */
  send<T = unknown>(name: string, data?: T): void;
  /**
   * Subscribe to a registered game event. `cb` runs with the event's JSON
   * payload each time the ECS emits `name`. Pass a type argument to type the
   * payload the callback receives.
   * @example bevy.on("frame", (f) => setFrame(f));
   * @example bevy.on<Frame>("frame", (f) => setFrame(f)); // f is Frame
   */
  on<T = any>(name: string, cb: (data: T) => void): void;
}

/** The superui JS↔Bevy bridge. See {@link Bevy}. */
declare const bevy: Bevy;

// The runtime aliases `window` to `globalThis`, so `window.bevy` works too.
interface Window {
  readonly bevy: Bevy;
}
