/**
 * Ambient type declarations for the `superui/test` authoring API.
 *
 * These types exist ONLY for the editor / TypeScript language server. superui's
 * `superui_test` CLI is the real consumer of `.spec.ts`: it strips the types and
 * erases the `import ... from "superui/test"` — `test`, `expect`, and `page` are
 * injected by the test-engine prelude. Nothing here affects the runtime; it only
 * powers autocomplete, hover docs, and type-checking.
 *
 * This surface mirrors `crates/superui_test_engine/src/prelude.js` EXACTLY. It is
 * intentionally NOT full Playwright: there is no `.not`, no `last()`, `hasText` is
 * a plain string, and every action/matcher resolves to `Promise<void>`.
 *
 * Do NOT edit this file inside a project — it is projected (copied) by
 * `cargo superui install` and will be overwritten. Edit the canonical copy at
 * `crates/superui/superui-test.d.ts`.
 */

declare module "superui/test" {
  /** Options for narrowing a `locator(...)` query. */
  export interface LocatorOptions {
    /**
     * Keep only elements whose text contains this substring. The runtime
     * stringifies the value, so pass a plain string (a RegExp is not supported).
     */
    hasText?: string;
  }

  /** A lazily-evaluated, chainable handle to DOM node(s), resolved when acted on. */
  export interface Locator {
    /** Narrow to descendants matching `selector` (optionally filtered by text). */
    locator(selector: string, options?: LocatorOptions): Locator;
    /** Select the match at `index` (0-based). */
    nth(index: number): Locator;
    /** Select the first match (alias for `nth(0)`). */
    first(): Locator;
    /** Click the resolved element, auto-waiting for it to appear. */
    click(): Promise<void>;
    /** Replace the resolved input's value with `text`. */
    fill(text: string): Promise<void>;
    /** Dispatch a key press to the resolved element. */
    press(key: string): Promise<void>;
    /** Hover the resolved element. */
    hover(): Promise<void>;
  }

  /** The mounted app page — the root from which locators are queried. */
  export interface Page {
    /** Start a locator query at the page root. */
    locator(selector: string, options?: LocatorOptions): Locator;
  }

  /** Auto-waiting assertions returned by `expect(...)`. Each resolves when it passes. */
  export interface Matchers {
    /** Assert the target is attached and not hidden. */
    toBeVisible(): Promise<void>;
    /** Assert the target's text content equals `text`. */
    toHaveText(text: string): Promise<void>;
    /** Assert the target resolves to exactly `count` nodes. */
    toHaveCount(count: number): Promise<void>;
    /** Assert the target's class list matches (RegExp source or literal string). */
    toHaveClass(expected: RegExp | string): Promise<void>;
    /** Assert the target has attribute `name` (optionally equal to `value`). */
    toHaveAttribute(name: string, value?: string): Promise<void>;
    /** Capture/compare a screenshot stored under `name`. */
    toHaveScreenshot(name: string): Promise<void>;
  }

  /** Arguments passed to each test body. */
  export interface TestArgs {
    page: Page;
  }

  /** Register a test. Bodies run against a per-spec mounted app. */
  export function test(name: string, fn: (args: TestArgs) => void | Promise<void>): void;

  /** Begin an assertion against a `Locator` or the `Page`. */
  export function expect(target: Locator | Page): Matchers;

  /** The page global; also delivered via each test's `{ page }` argument. */
  export const page: Page;
}
