[package]
name = "cargo-superui"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "CLI to scaffold superui editor types & tsconfig into a project"
repository.workspace = true
keywords = ["bevy", "superui", "cli", "cargo-subcommand"]

[lib]
name = "superui_cli"
path = "src/lib.rs"

[[bin]]
name = "cargo-superui"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
